version: '2'

services:
  rabbitmq:
    restart: always
    container_name: rabbitmq
    image: rabbitmq:3.6.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=muon
      - RABBITMQ_DEFAULT_PASS=microservices
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    networks:
        - default
        - muon

  photon:
    restart: always
    image: simplicityitself-muon-image.jfrog.io/photon-lite:0.0.3
    environment:
      - MUON_URL=amqp://muon:microservices@rabbitmq
    links:
      - rabbitmq
    networks:
        - default
        - muon
    command: -type h2 -muonurl amqp://muon:microservices@rabbitmq -h2path /tmp/photon

  gateway:
    restart: always
    image: simplicityitself-muon-image.jfrog.io/muonjs-gateway:latest
    environment:
      - MUON_URL=amqp://muon:microservices@rabbitmq
    links:
      - rabbitmq
    ports:
      - "9898:9898"
    networks:
        - default
        - muon

networks:
    muon:
      external: true
